default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hayato_development

test:
  <<: *default
  database: hayato_test

production:
  <<: *default
  database: hayato_production
  username: hayato
  password: <%= ENV['HAYATO_DATABASE_PASSWORD'] %>
